### ISSUE TITLE
Edit label in replace lavbel tab don't make the model dirty

### ISSUE THREAD

**Issue by Ridderby** [archi-contribs/specialization-plugin#12]
If I open a model and make changes to an objects replace-label in the dedicated property-tab it does not make the model dirty and changes are not saved if I press Save (non-dirty models are not saved).

(Super-plugin by the way, many thanks!)

**Comment by herve91** [comment]
Hi,

Thanks for your kind comment and for pointing out this bug. I'll correct it asap.

Best regards
Hervé

**Comment by herve91** [comment]
solved in version 1.0.2

Best regards
Hervé
