### ISSUE TITLE
Nested objects of same color have shades of the color 

### ISSUE THREAD

**Issue by peterprib** [archi-contribs/specialization-plugin#16]
If I nest to objects in diagram I am having to manual arrange different shades of color to improve diagram.  Great if shading was automated.  Only need to oscillate between two shades which could be set as defaults and overwritten at preferences and view layers

**Comment by jbsarrodie** [comment]
Hi,

FYI, this will be made possible in Archi itself in upcoming version 4.3 through the addition of a transparency setting to diagram elements.

For example:
* if toplevel and nested elements have the same color with transparency set, then inner elements will be "darker"
* if toplevel element has a color (without transparency) and nested elements are white with transparency set, then inner elements will be "lighter"

**Comment by herve91** [comment]
Thanks a lot JB.

So I can close this request :)
