### ISSUE TITLE
Disapearing of alignement and sizing option 

### ISSUE THREAD

**Issue by dchaveneau** [archi-contribs/specialization-plugin#17]
The installation of the 1.0.7 version make disappear the alignement and sizing options.

I tried to uninstall the plugin, the options appeared. Then they disappeared again while installing again.

**Comment by herve91** [comment]
Thanks a lot for pointing this bug out.

I do not use these options so I must admit that they are not in my checking list.

I just released the version 1.0.7.1 that restore them.

Best regards.
Hervé
