### ISSUE TITLE
Default icon position on 3D shapes

### ISSUE THREAD

**Issue by rich-biker** [archi-contribs/specialization-plugin#18]
This might be "nice to have", but I'm wondering if it would be convenient to have the default position on 3D shapes to be on the front face of the shape, rather than up the corner. 

This example shows Plateau 1 with the default location. The icon feels lost to me.
I have set Plateau 2 icon location to -15,-15. This brings it to the front face.

![icon location](https://user-images.githubusercontent.com/18450552/45411841-2f890700-b66d-11e8-8ef1-432abf8c9d65.png)

**Comment by herve91** [comment]
Hi,

My apologies for this late answer.

I added your request on my todo list.

Thanks
Hervé

**Comment by rich-biker** [comment]
Sorry it have you sleepless nights. It's looking great now and works beautifully on all the 3d shapes..

<img width="236" alt="image" src="https://user-images.githubusercontent.com/18450552/47202399-dfd8e200-d374-11e8-96db-30c35e4c6b00.png">

Thankyou!
I'll close this.
