### ISSUE TITLE
Custom icons not showing up

### ISSUE THREAD

**Issue by ubibene** [archi-contribs/specialization-plugin#2]
- Archimatetool 4.0.3
- OS is linuxmint 18

I followed the instructions (plugin installation, model setup, icon images copied to plugins/com.archimate.../img/mydirectory ) but icons are not showing up

Enabling the  plugin traces gives : 

`
!
2017-11-03 20:33:00 INFO   144:SpecializationPlugin           - Initialising SpecializationPlugin plugin ...

2017-11-03 20:33:00 INFO   146:SpecializationPlugin           - ===============================================

2017-11-03 20:33:00 INFO   196:SpecializationPlugin           - Specialization plugin v0.2 initialized.

tail: /home/xxx/SpecializationPlugin.log : fichier tronqué
`

Icon is attached

![rect](https://user-images.githubusercontent.com/16741615/32392851-8c4c2882-c0d7-11e7-8580-8871af16578a.png)

**Comment by rich-biker** [comment]
Are you also creating the property called 'icon' for each shape where you want to use it, with the value of 'img/mydirectory/iconname.png' 

The suffix is sometimes necessary, I've found.

**Comment by herve91** [comment]
Hi,

I've been communicating with Ubibene using emails and forgot to summarize the status here. Sorry about that.

Ubibene was trying to put an icon on data objects. The point is that this object does not have any icon, it just has got an horizontal line across its shape.

My plugin is able to replace existing icons, not add icons on objects that do not have any so at the moment it cannot put any icon on data objects.

As for the log file, he was not in trace mode. That's the reason why the log file did not contain any message after the initialization.

I close this issue.

**Comment by ubibene** [comment]
as a matter of fact, the problem does exist with other kind of archimate objects (application components, , nodes, ....) on 

- Linux mint 18.2 64 bits
- java-1.8.0-openjdk-amd64
- archi 4.0.3

**Comment by herve91** [comment]
Hi Ubibene,

I just installed a fresh Linux Mint 18.2 (64bit) with the default jre, and the icons work as expected.

but I  did not see java-1.8.0-openjdk-amd64 in the available package list

**Comment by grv87** [comment]
@herve91, no new ideas on this issue?

Maybe this is just my use case, but I have much more artifacts and data objects that anything else. So they could benefit most from having icons to distinguish by types.
