### ISSUE TITLE
Error "Failed to create the part's controls" after copying the jar file

### ISSUE THREAD

**Issue by WKS-Sim** [archi-contribs/specialization-plugin#21]
Hello,

I copied the jar file org.archicontribs.specialization_v1.0.9.jar into the plugin folder C:\Program Files\Archi4\plugins (using Archimate 4.2.0). 
When restarting Archi I get this error:
_"Failed to create the part's controls"
java.lang.ClassCastException: com.archimatetool.model.impl.DiagramModelArchimateObject cannot be cast to com.archimatetool.model.IArchimateModelObject
..._
When creating a noew object the error is
_An error has occurred. See error log for more details.
com.archimatetool.model.impl.DiagramModelArchimateObject cannot be cast to com.archimatetool.model.IArchimateModelObject_

Any idea what could be the reason and how to fix it ?

Thanks and best regards
Werner

**Comment by herve91** [comment]
Hi,

3 options:
   1 - upgrade Archi to version 4.3
   2 - downgrade the plugin to [version 1.0.7.1](https://github.com/archi-contribs/specialization-plugin/raw/2362f0b2a4a04e8630e6b2438f31e6dd76af8400/org.archicontribs.specialization_v1.0.7.1.jar)
  3 - wait few days until I fix it :-)

Best regards
Hervé

**Comment by WKS-Sim** [comment]
Perfect, upgrading to Archi 4.3 did the job - thank you for your fast support.
Thank you and best regards
Werner
