### ISSUE TITLE
null pointer exception when switching between views with Specialization plugin drill-down

### ISSUE THREAD

**Issue by timhale7** [archi-contribs/specialization-plugin#24]
ug report - null pointer exception

attaching configuration file and error log snippet
Version of Archi, Operating System

help/about says Archi Version 4.3.1 Build 2019-01281101 - but the download package says 4.3.2
Windows 10

I am using the Specialization plug-in, and its drill-down feature to jump to another view when I double-click an object . This would be the current plug-in version, as I downloaded it earlier this week.
https://github.com/archi-contribs/specialization-plugin
Steps to Reproduce the Behaviour

    I have one view dedicated to navigation - I happened to use "work package" objects for this, since I don't use them in the model otherwise. I have one object per view, with the drill-down property linked to one of the views. 19 views in all.
    I have one "work package" object on each of the 19 views with its drill down property set to the navigation page. trying to make it easy for the novice user to navigate around the models.
    When I jump to a model via a double-click on the object, and then close the eclipse page via the "x'. I get the null pointer exception - sometimes. I also get it - sometimes - when I jump from one eclipse tab to another. It ONLY occurs when I've changing between views, never when I'm doing basic modeling functions on a view. Once it starts to occur, then it seems to occur every time I switch views.

[null pointer exception - configuration.txt](https://github.com/archi-contribs/specialization-plugin/files/2818527/null.pointer.exception.-.configuration.txt)

[null pointer exception - error log.txt](https://github.com/archi-contribs/specialization-plugin/files/2818529/null.pointer.exception.-.error.log.txt)

**Comment by Phillipus** [comment]
Closing this as it's an Archi bug.
