### ISSUE TITLE
Make image folder and property name customizable

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/specialization-plugin#3]
Hi,

I've started to experiment with this plugin and I have a use case where I'd like to use another property name. The reason is that for several models I use a property named "Stereotype" which value is the type of customized element. Being able to defined that this property drives the choice of the image would be great and a first step in Archi supporting ArchiMate language customization mecanisms. In addition, the location of the image folder should be customizable too as not all users have write access to the Archi setup folder.

That being said: Great work !

Regards,

**Comment by herve91** [comment]
Hi JB,

Fair enough, I will add an option to change the property name.

Regarding the images location, I failed to put it outside the "img" folder of the editor plugin because I did not rewrite the whole icon process, but only change the icon name calculated by the editor plugin. But I will try harder :)

If you've got some idea on how to do it, please feel free to drop me a line :)

**Comment by jbsarrodie** [comment]
>Fair enough, I will add an option to change the property name.

Great!

>If you've got some idea on how to do it, please feel free to drop me a line :)

I'll look at your code to help you on that (we did it for the model-repository-plugin)

**Comment by herve91** [comment]
Hi JB,

Sorry it took so long. The new 0.3 version allows to change the property name on a view by view basis "replace icons property" and "replace labels property").

Please do not hesitate to tell me if this does not suit your needs.

Best regards
Hervé

**Comment by jbsarrodie** [comment]
Hi Hervé,

Thank you for the update. I'll have to test it.

> The new 0.3 version allows to change the property name on a view by view basis 

Do we also have a way to globally set it (e.g. in my case it will always be "Stereotype" so I don't want to have to add a property on each and every views...

**Comment by herve91** [comment]
I did not think about it, but can easily do it.

I can even extend it to something like:
   1. check for the existence of the "replace icon property" on the element itself
   2. if it does not exist, check the existence of the "replace icon**s** property" on the view
   3. if it does not exist, check the existence of the "replace icon**s** property" on the model

Would it suit your need ?

**Comment by jbsarrodie** [comment]
>Would it suit your need ?

Short answer: yes ;-)

**Comment by herve91** [comment]
Ok, so I'll do it :-)

**Comment by herve91** [comment]
Hi JB,

It's done. It will be in the next release.

Best regards
Hervé

**Comment by herve91** [comment]
I just released the version 1.0 of my plugin.

Please do not hesitate to open a new issue if this does not work as expected.
