### ISSUE TITLE
Issue when replacing icons and the collaboration plug.

### ISSUE THREAD

**Issue by KingBain** [archi-contribs/specialization-plugin#32]
When I replace an icon, commit the changes and push the model to a git repo. The graphic doesnt get included with the git push.

Is there a way to have the collaboration plugin capture and upload the icons used in the specialization ?

I'm trying to think of a way to share the images with multiple people who are working on the same model.

Instead of using local images, could we specify a url path to a graphic  ?

**Comment by herve91** [comment]
Unfortunately, the v1 version is only able to use external images from the file-system.

But the v2 version stores the images inside the model so they are captured by the collaboration plugin. It is still in alpha stage but new versions will be released soon.
