### ISSUE TITLE
v2.0.0: Feature proposal: Keep existing element icon

### ISSUE THREAD

**Issue by cs2ea** [archi-contribs/specialization-plugin#33]
Hello, 

I really like this new version of the plugin - the approach is very clean and understandable. 

One suggestion would be to be able to add the new image to the element without removing the default one, e.g.:

![image](https://user-images.githubusercontent.com/44928155/59556203-f9dbca80-8fbe-11e9-8a66-30ea25332e21.png)

The general meaning of the element would thus remain directly visible and would be complemented by the new image. 

Thank you!

**Comment by herve91** [comment]
Hi,

The core of Archi only allow one single icon, and only on some components (some components do not even have an icon), and unfortunately, I cannot add a new one.

Sorry.
