### ISSUE TITLE
Use concept type for label

### ISSUE THREAD

**Issue by kvaleev** [archi-contribs/specialization-plugin#42]
I try to implement the "Mastering of Archimate" labeling scheme with Archi and don't know if it possible (can't figure out it by myself or find in documentation) to set an Archimate concept type (Application Component or Bussiness Service for instance) of the element as its label property?

**Comment by jbsarrodie** [comment]
Hi,

Archi 4.7 (available in [Early Access](https://www.archimatetool.com/beta/)) now implements a similar feature and supports everything needed to use "Mastering ArchiMate" labeling scheme.

This is still being improved and you can follow discussions [here](https://github.com/archimatetool/archi/issues/576#issuecomment-612818087).

Label expressions are documented [here](https://github.com/archimatetool/archi/wiki/Label-Expressions)

**Comment by kvaleev** [comment]
Great, thanks!
