### ISSUE TITLE
Compatibility with report feature ?

### ISSUE THREAD

**Issue by mbibim** [archi-contribs/specialization-plugin#45]
Hello,

ty for this plugin ... works perfectly in ARCHI and creates a better experience using the application.

How can i make it work fine with ARCHI, report HTML feature ?

Regards

**Comment by herve91** [comment]
It won't I'm afraid as it could mean completely redevelop the HTML export feature.

But Archi 4.7 now natively includes the ability to change concepts labels on a per view basis. So if this is what you're using from my plugin, you may do it through Archi without the use of any plugin.

I close this case as there is nothing I can do regarding html reports.

**Comment by mbibim** [comment]
thank you very much for your answer. My point was more about pictures than labels.

**Comment by herve91** [comment]
For pictures, there is no solution I'm afraid.

**Comment by mbibim** [comment]
:( develop another export ...

**Comment by mbibim** [comment]
FYI i just found the right way to do it using canvas ! i've got exactly the same result and it works fine with the html report feature. thanks again

**Comment by herve91** [comment]
Thanks for the info
