### ISSUE TITLE
The Archi's Preference Page of the Specialization Plugin is not complete with Archi 4.7.1 (on windows)

### ISSUE THREAD

**Issue by geraldmorisseau** [archi-contribs/specialization-plugin#46]
![image](https://user-images.githubusercontent.com/5775450/100583984-c6dce200-32eb-11eb-95da-116342c743a3.png)

**Comment by geraldmorisseau** [comment]
Here is the log 
[SpecializationPlugin.log](https://github.com/archi-contribs/specialization-plugin/files/5614543/SpecializationPlugin.log)
:

**Comment by herve91** [comment]
The preference page renders well, there is nothing to show on the preference page. Please see case #43
