### ISSUE TITLE
Version 1.x of plugin needs to be compiled against Archi 4.7.x to address API changes

### ISSUE THREAD

**Issue by sudr** [archi-contribs/specialization-plugin#47]
I'm routinely seeing the following error's being thrown by the 1.x version of this plugin on Arch 4.7.x

An error has occurred. See error log for more details.
org.archicontribs.specialization.uiProvider.elements.figures.ApplicationComponentFigure.setText()V

It appears that the plugin needs to be updated and compiled against Archi 4.7.x.

**Comment by herve91** [comment]
You're right ...

I did it for version 2 ... I need to do the same with version 1 ...

**Comment by herve91** [comment]
Done ... Please upgrade to version 1.0.12

Best regards
Hervé

**Comment by sudr** [comment]
Thank you. Works as expected now. Appreciate the quick turnaround.
