### ISSUE TITLE
Support for more element types

### ISSUE THREAD

**Issue by evlibra** [archi-contribs/specialization-plugin#48]
Why "replace icon" cant be available for all element types? It would be good to add it at least for Representation and Dataobject. Thanks.

**Comment by herve91** [comment]
I can replace icons of Archi elements that have got one. Those that haven't got an icon at all cannot be changed.

**Comment by jbsarrodie** [comment]
Hi,

FYI, Phil and I are working on native support for custom icons. This should be added in Archi in the next 3-6 months.

Here's an example of what could be done:
![](https://pbs.twimg.com/media/EnmSUHcWMAE84DT?format=png&name=large)

**Comment by herve91** [comment]
Hi JB,

I'm impressed ... This looks very nice ... As always :-)

My specialization plugin won't be necessary anymore, even the version 2 (that I started but never had time to develop it) :-)

**Comment by jbsarrodie** [comment]
> I'm impressed ... This looks very nice ... As always :-)

Well, all credits for you. This will mostly be re-implementation of your plugin. Of course with a better intergration and some small additions, but you did it first ;-)

**Comment by evlibra** [comment]
That is great news. Would it be compatible with models created using specialization plugin? E.g. able to show icons which used to be created earlier using the plugin. Thanks.

**Comment by jbsarrodie** [comment]
> That is great news. Would it be compatible with models created using specialization plugin? E.g. able to show icons which used to be created earlier using the plugin. Thanks.

It won't be possible because Herve uses a property, meaning that icon is always use once defined, while we'll set it at the view level like any appearance attribute.
