### ISSUE TITLE
Drill-down Elements navigation on HTML-reports

### ISSUE THREAD

**Issue by evlibra** [archi-contribs/specialization-plugin#49]
Similar to how it is done for View Reference. As I've understood the issue is how to distinguish selection-click in HTML (for documentation) and navigation click, which is double-click in the application (for opening another drill-down element)? Probably, it could be done by replication of drill-down property by clickable icon?

1) HTML-report preview with drill-down on (see "Hip Flexors" element): https://evlibra.github.io/Archi_Body/198667f9-f68d-46a1-8bf6-01c97c861d17/views/b90805b2-7a2c-47e2-86a7-b2d5d1dd95a6.html

2) HTML-report preview with View Reference (see blue "SWE.1" and "ASPICE - PRJ X - Map" for example)
https://evlibra.github.io/Archi_ASPICE/id-322369a4-b2ad-4c96-8d58-a5d264295809/views/b4a58a17-a562-4304-b735-3b37cc0d68d2.html

**Comment by herve91** [comment]
The plugin already implement drill-down for all Archi elements ... while you are in Archi.

Unfortunately, It won't work in HTML reports.
