### ISSUE TITLE
Deletion or replace of images from icon pallete

### ISSUE THREAD

**Issue by peterprib** [archi-contribs/specialization-plugin#51]
Needed to replace and ICON with a different version.  Couldn't see a way to replace or delete redundant images

**Comment by herve91** [comment]
Hi Peter,

You're right, there is not such option to replace an ICON in all objects at once. You need to replace it object per object.

As the core Archi is working on natively deal with specializations, I believe it is not worth updating my plugin ;-)

Best regards
Hervé
