### ISSUE TITLE
Ability to have the archimate icon along with a new icon

### ISSUE THREAD

**Issue by peterprib** [archi-contribs/specialization-plugin#52]
Want to keep the orginal archi icon but would love to have a secondary icon or as the back drop image that fills the node box.

**Comment by herve91** [comment]
Hi Peter,

At the moment, my plugin is quite simple: it replaces the native icon drawing function by a specific one. Adding a second icon would require to rewrite much more code.

And as Archi will nativelly handle specialization, my plugin will not be usefull anymore so I won't go this way. Sorry ...

**Comment by Phillipus** [comment]
> And as Archi will nativelly handle specialization, my plugin will not be usefull anymore so I won't go this way. Sorry ...

Hi Herve, I just want to say that your plug-in has been highly appreciated by very many users! Yes we are implementing specialization in Archi with icons, but we must all remember that you did it first!

Regards,

Phil

**Comment by herve91** [comment]
Thanks a lot Phil but my work would be nothing without yours :)
