### ISSUE TITLE
Doesn't work with Archi 4.8.1

### ISSUE THREAD

**Issue by thinkdil** [archi-contribs/specialization-plugin#53]
The icon plugin doesnot work with recent upgrade of Archi 4.8.1
Could you recompile against 4.8.1 and publish. Thanks

**Comment by herve91** [comment]
Archi 4.9 natively includes specialisation. Therefore my plugin is quite outdated.
I suggest you have a look to the alpha release of Archi 4.9.

**Comment by thinkdil** [comment]
Thanks @herve91. Will try out 4.9. Great work :)

**Comment by herve91** [comment]
If 4.9 doesn't suit your need, please do not hesitate to tell me and I will recompile against 4.8.1.
