### ISSUE TITLE
[Issue] Work Package has gone rectangular

### ISSUE THREAD

**Issue by rich-biker** [archi-contribs/specialization-plugin#7]
**Version of Archi, Operating System**

Archi 4.1.1 64bit on Mac (or PC).
Specialization plug-in 0.3

**Expected Behaviour**

Work Package element appearance used to have rounded corners.

**Actual Behaviour**

The Work Package element appears as a rectangle.

This seems to have appeared at some point since I started using the Collaboration, forms or specialisation plug-ins. I don't really want to strip them out, but downloading a fresh Archi seems to be ok again.

![wp](https://user-images.githubusercontent.com/18450552/33844109-331efd2e-de97-11e7-94d2-5b6c9d17b6cc.png)

The other round-corner shapes seem fine, as far as I can tell.

**Comment by herve91** [comment]
Hi,

Thanks for pointing this error to me. I'll have a look asap and let you know.

Best regards
Hervé

**Comment by herve91** [comment]
Hi,

I've found the isue. It will be corrected in the next release.

Best regards
Hervé

**Comment by herve91** [comment]
I just released the version 1.0 of my plugin.

Please do not hesitate to open a new issue if this does not work as expected.
