### ISSUE TITLE
Per element Properties to scale the source image

### ISSUE THREAD

**Issue by lonniev** [archi-contribs/specialization-plugin#8]
My goal is to be able to record screen snapshots as UI/UX mockups in "Application Interface" elements.

Today, screen snapshots at full resolution can be immense. For example, 38 inches wide on some monitors.

Within an Archi view, I want to show a scaled (down) version of the snapshot. For example, to make "Powerpoint" like views.

Ideally, a property would control whether the source image is automatically fit-within-element, cropped-by-element, or fits-element-to-actual-size.

Additionally, properties to snap the icon to left, top, right, bottom, and center of the element would be a nice feature.

**Comment by herve91** [comment]
I already added a new property called "icon size" that allows to
     - either specifying the image width (then the height is calculated to keep the image ratio)
     - either specifying the image height (then the width is calculated to keep the image ratio)
     - either specifying that the image should be scaled to fit into the element's rectangle

it will be available in the next release.

At the moment, the only thing that my plugin does it to read the image from the file, resize it, and pass it to Archi. Changing the icon location would require to rewrite a big part of Archi graphical user interface, which would be quite very complicated. I will study if I find an easier way to do it, but until then, it will not be on my todo list. Sorry.

**Comment by lonniev** [comment]
Very good. I’m pleased with the first capability and understand that the
second would be far more difficult.



-- 
Lonnie VanZandt
303-900-3048

On 16 December 2017 at 15:38:25, herve91 (notifications@github.com) wrote:

I already added a new property called "icon size" that allows to
- either specifying the image width (then the height is calculated to keep
the image ratio)
- either specifying the image height (then the width is calculated to keep
the image ratio)
- either specifying that the image should be scaled to fit into the
element's rectangle

it will be available in the next release.

At the moment, the only thing that my plugin does it to read the image from
the file, resize it, and pass it to Archi. Changing the icon location would
require to rewrite a big part of Archi graphical user interface, which
would be quite very complicated. I will study if I find an easier way to do
it, but until then, it will not be on my todo list. Sorry.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/archi-contribs/specialization-plugin/issues/8#issuecomment-352216870>,
or mute the thread

**Comment by herve91** [comment]
I've go good news for you.

Positioning the image is much easier than I thought. Next release will allow you to specify the position through a "icon position" property with a value under the form "x,y" where:
- x is the horizontal position
   * "center" keyword means center the image horizontally in the element's rectangle
   * positive value specifies the margin between the image and the left border
   * negative value specifies the margin between the image and the right border
- y is the horizontal position
   * "center" keyword means center the image vertically in the element's rectangle
   * positive value specifies the margin between the image and the top border
   * negative value specifies the margin between the image and the bottom border

**Comment by lonniev** [comment]
rockstar



-- 
Lonnie VanZandt
303-900-3048

On 18 December 2017 at 15:37:05, herve91 (notifications@github.com) wrote:

I've go good news for you.

Positioning the image is much easier than I thought. Next release will
allow you to specify the position through a "icon position" property with a
value under the form "x,y" where:

   - x is the horizontal position
      - "center" keyword means center the image horizontally in the
      element's rectangle
      - positive value specifies the margin between the image and the left
      border
      - negative value specifies the margin between the image and the right
      border
   - y is the horizontal position
      - "center" keyword means center the image vertically in the element's
      rectangle
      - positive value specifies the margin between the image and the top
      border
      - negative value specifies the margin between the image and the
      bottom border

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/archi-contribs/specialization-plugin/issues/8#issuecomment-352580368>,
or mute the thread

**Comment by herve91** [comment]
I just released the version 1.0 of my plugin.

Please do not hesitate to open a new issue if this does not work as expected.
